const wilders = [
    {
        id:1,
        firstName:"Ryota",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:1,
            skillName:"PHP"
        },
        {
            id:2,
            skillName:"javascript"
        },
        {
            id:3,
            skillName:"react"
        },
        
        ]
    },
    {
        id:2,
        firstName:"Alan",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:3,
        firstName:"Hayato",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:4,
        firstName:"Leo",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:5,
        firstName:"Ryuto",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:7,
        firstName:"Hiro",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:4,
        firstName:"yuta",
        lastName:"wild",
        isTrainer:false,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
    {
        id:4,
        firstName:"yuta",
        lastName:"wild",
        isTrainer:true,
        skills:[
        {
            id:2,
            skillName:"javascript"
        }
        ]
    },
]

export default wilders